
project_id = "oirsouqyqodryfvuxwbr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = [
  "https://localhost:8080/auth/callback",
  "http://localhost:5173/auth/callback", 
  "http://localhost:3000/auth/callback",
  "https://oirsouqyqodryfvuxwbr.lovable.dev/auth/callback"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
url = "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"

[functions]
[functions.process-payment]
verify_jwt = false

[functions.auth-emails]
verify_jwt = false
