// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oirsouqyqodryfvuxwbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pcnNvdXF5cW9kcnlmdnV4d2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTczNzYsImV4cCI6MjA1NjU5MzM3Nn0.9iuORXOHXlxcCMhdFYP19GSfbaiMjWaJqKErRhH8cFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);